#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: f4a13a5
#
Name     : libedit
Version  : 20250104.3.1
Release  : 26
URL      : https://www.thrysoee.dk/editline/libedit-20250104-3.1.tar.gz
Source0  : https://www.thrysoee.dk/editline/libedit-20250104-3.1.tar.gz
Summary  : command line editor library provides generic line editing, history, and tokenization functions.
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause-UC
Requires: libedit-lib = %{version}-%{release}
Requires: libedit-license = %{version}-%{release}
Requires: libedit-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : groff
BuildRequires : ncurses-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the libedit package.
Group: Development
Requires: libedit-lib = %{version}-%{release}
Provides: libedit-devel = %{version}-%{release}
Requires: libedit = %{version}-%{release}

%description dev
dev components for the libedit package.


%package lib
Summary: lib components for the libedit package.
Group: Libraries
Requires: libedit-license = %{version}-%{release}

%description lib
lib components for the libedit package.


%package license
Summary: license components for the libedit package.
Group: Default

%description license
license components for the libedit package.


%package man
Summary: man components for the libedit package.
Group: Default

%description man
man components for the libedit package.


%prep
%setup -q -n libedit-20250104-3.1
cd %{_builddir}/libedit-20250104-3.1
pushd ..
cp -a libedit-20250104-3.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736180250
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736180250
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libedit
cp %{_builddir}/libedit-20250104-3.1/COPYING %{buildroot}/usr/share/package-licenses/libedit/23d54f3ac85bc67716a2591c090796b0937433eb || :
export GOAMD64=v2
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/share/man/man3/history.3
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/editline/readline.h
/usr/include/histedit.h
/usr/lib64/libedit.so
/usr/lib64/pkgconfig/libedit.pc
/usr/share/man/man3/editline.3
/usr/share/man/man3/el_deletestr.3
/usr/share/man/man3/el_end.3
/usr/share/man/man3/el_get.3
/usr/share/man/man3/el_getc.3
/usr/share/man/man3/el_gets.3
/usr/share/man/man3/el_history.3
/usr/share/man/man3/el_history_end.3
/usr/share/man/man3/el_history_init.3
/usr/share/man/man3/el_history_w.3
/usr/share/man/man3/el_history_wend.3
/usr/share/man/man3/el_history_winit.3
/usr/share/man/man3/el_init.3
/usr/share/man/man3/el_init_fd.3
/usr/share/man/man3/el_insertstr.3
/usr/share/man/man3/el_line.3
/usr/share/man/man3/el_parse.3
/usr/share/man/man3/el_push.3
/usr/share/man/man3/el_reset.3
/usr/share/man/man3/el_resize.3
/usr/share/man/man3/el_set.3
/usr/share/man/man3/el_source.3
/usr/share/man/man3/el_tok_end.3
/usr/share/man/man3/el_tok_init.3
/usr/share/man/man3/el_tok_line.3
/usr/share/man/man3/el_tok_reset.3
/usr/share/man/man3/el_tok_str.3
/usr/share/man/man3/el_tok_wend.3
/usr/share/man/man3/el_tok_winit.3
/usr/share/man/man3/el_tok_wline.3
/usr/share/man/man3/el_tok_wreset.3
/usr/share/man/man3/el_tok_wstr.3
/usr/share/man/man3/el_wdeletestr.3
/usr/share/man/man3/el_wget.3
/usr/share/man/man3/el_wgetc.3
/usr/share/man/man3/el_wgets.3
/usr/share/man/man3/el_winsertstr.3
/usr/share/man/man3/el_wline.3
/usr/share/man/man3/el_wparse.3
/usr/share/man/man3/el_wpush.3
/usr/share/man/man3/el_wset.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libedit.so.0.0.75
/usr/lib64/libedit.so.0
/usr/lib64/libedit.so.0.0.75

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libedit/23d54f3ac85bc67716a2591c090796b0937433eb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/editrc.5
/usr/share/man/man7/editline.7
