#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
Name     : libedit
Version  : 20221030.3.1
Release  : 21
URL      : https://www.thrysoee.dk/editline/libedit-20221030-3.1.tar.gz
Source0  : https://www.thrysoee.dk/editline/libedit-20221030-3.1.tar.gz
Summary  : command line editor library provides generic line editing, history, and tokenization functions.
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause-UC
Requires: libedit-lib = %{version}-%{release}
Requires: libedit-license = %{version}-%{release}
Requires: libedit-man = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : groff
BuildRequires : ncurses-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package dev
Summary: dev components for the libedit package.
Group: Development
Requires: libedit-lib = %{version}-%{release}
Provides: libedit-devel = %{version}-%{release}
Requires: libedit = %{version}-%{release}

%description dev
dev components for the libedit package.


%package lib
Summary: lib components for the libedit package.
Group: Libraries
Requires: libedit-license = %{version}-%{release}

%description lib
lib components for the libedit package.


%package license
Summary: license components for the libedit package.
Group: Default

%description license
license components for the libedit package.


%package man
Summary: man components for the libedit package.
Group: Default

%description man
man components for the libedit package.


%prep
%setup -q -n libedit-20221030-3.1
cd %{_builddir}/libedit-20221030-3.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689801536
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1689801536
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libedit
cp %{_builddir}/libedit-20221030-3.1/COPYING %{buildroot}/usr/share/package-licenses/libedit/23d54f3ac85bc67716a2591c090796b0937433eb || :
%make_install
## Remove excluded files
rm -f %{buildroot}*/usr/share/man/man3/history.3

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/editline/readline.h
/usr/include/histedit.h
/usr/lib64/libedit.so
/usr/lib64/pkgconfig/libedit.pc
/usr/share/man/man3/editline.3
/usr/share/man/man3/el_deletestr.3
/usr/share/man/man3/el_end.3
/usr/share/man/man3/el_get.3
/usr/share/man/man3/el_getc.3
/usr/share/man/man3/el_gets.3
/usr/share/man/man3/el_init.3
/usr/share/man/man3/el_init_fd.3
/usr/share/man/man3/el_insertstr.3
/usr/share/man/man3/el_line.3
/usr/share/man/man3/el_parse.3
/usr/share/man/man3/el_push.3
/usr/share/man/man3/el_reset.3
/usr/share/man/man3/el_resize.3
/usr/share/man/man3/el_set.3
/usr/share/man/man3/el_source.3
/usr/share/man/man3/el_wdeletestr.3
/usr/share/man/man3/el_wget.3
/usr/share/man/man3/el_wgetc.3
/usr/share/man/man3/el_wgets.3
/usr/share/man/man3/el_winsertstr.3
/usr/share/man/man3/el_wline.3
/usr/share/man/man3/el_wparse.3
/usr/share/man/man3/el_wpush.3
/usr/share/man/man3/el_wset.3
/usr/share/man/man3/history_end.3
/usr/share/man/man3/history_init.3
/usr/share/man/man3/history_w.3
/usr/share/man/man3/history_wend.3
/usr/share/man/man3/history_winit.3
/usr/share/man/man3/tok_end.3
/usr/share/man/man3/tok_init.3
/usr/share/man/man3/tok_line.3
/usr/share/man/man3/tok_reset.3
/usr/share/man/man3/tok_str.3
/usr/share/man/man3/tok_wend.3
/usr/share/man/man3/tok_winit.3
/usr/share/man/man3/tok_wline.3
/usr/share/man/man3/tok_wreset.3
/usr/share/man/man3/tok_wstr.3

%files lib
%defattr(-,root,root,-)
/usr/lib64/libedit.so.0
/usr/lib64/libedit.so.0.0.70

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libedit/23d54f3ac85bc67716a2591c090796b0937433eb

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man5/editrc.5
/usr/share/man/man7/editline.7
