#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libedit
Version  : 20160903
Release  : 7
URL      : http://thrysoee.dk/editline/libedit-20160903-3.1.tar.gz
Source0  : http://thrysoee.dk/editline/libedit-20160903-3.1.tar.gz
Summary  : command line editor library provides generic line editing, history, and tokenization functions.
Group    : Development/Tools
License  : BSD-3-Clause BSD-4-Clause-UC
Requires: libedit-lib
Requires: libedit-doc
BuildRequires : groff
BuildRequires : ncurses-dev

%description
No detailed description available

%package dev
Summary: dev components for the libedit package.
Group: Development
Requires: libedit-lib
Provides: libedit-devel

%description dev
dev components for the libedit package.


%package doc
Summary: doc components for the libedit package.
Group: Documentation

%description doc
doc components for the libedit package.


%package lib
Summary: lib components for the libedit package.
Group: Libraries

%description lib
lib components for the libedit package.


%prep
%setup -q -n libedit-20160903-3.1

%build
export LANG=C
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/include/editline/readline.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*
%doc /usr/share/man/man7/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
